# Generated by Django 6.0.5 on 2026-05-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicicletas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to=settings.AUTH_USER_MODEL)),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='rentals.bicicleta')),
            ],
        ),
    ]
